### PR TITLE
Fix:  call reset and restore event triggers; amended "soft" reset condition; prevent `reload` from being called when an assessment is launched

### LINKED ISSUE #2: Reset and restore event triggers
`reset` and `restore` methods should call super Class to trigger the relevant events. See https://github.com/adaptlearning/adapt-contrib-scoring/pull/9.

### LINKED ISSUE #4: navigation back button
When in an assessment, the navigation back button doesn't change the location because the `reload` method is erroneously called when the assessment is launched, which then replaces the last Backbone.history entry.

The `canReload` method needs to account for whether the assessment article is already rendered before calling `reload` during a `reset`.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #2, #3, #4.

### Fix
* Amended "soft" reset logic so all associated components have to be configured for a "soft" reset, to allow an assessment to remain complete following a reset.
* Ensure all reset and restore events are triggered
* Prevent `reload` from being called when an assessment is launched, which broke the navigation back button.

### Dependency
* https://github.com/adaptlearning/adapt-contrib-scoring/pull/9

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/AssessmentSet.js [hunk 1]
```diff
@@ -397,7 +400,7 @@ export default class AssessmentSet extends ScoringSet {
   get isComplete() {
     if (this.isAwaitingChildren || !this.isAvailable) return false;
     if (this.attempt?.isInSession) return this.isAttemptComplete;
-    if (this.hasSoftReset) return this.attempts.wasComplete;
+    if (this.iSoftReset) return this.attempts.wasComplete;
```
Comment (oliverfoster) [inline js/AssessmentSet.js:403]:
```suggestion
    if (this.isSoftReset) return this.attempts.wasComplete;
```

`isSoftReset` not `iSoftReset` throughout

Comment (danielghost) [reply js/AssessmentSet.js]: Thanks for spotting. Had is typed properly in https://github.com/adaptlearning/adapt-contrib-scoringAssessment/pull/6 which was closed as ended up as a duplicate of this PR, so I shouldn't have made this mistake.

**Review by oliverfoster — APPROVED** [review]
