### PR TITLE
Fix: inaccurate compatibility state.

### LINKED ISSUE #10: inaccurate compatibility state
The `_compatibilityState` for backwards compatibility can return inaccurate attributes.

`questionCount` is based on the models rather than the questions specifically. `attemptInProgress is always false. `lastAttemptScoreAsPercent` is always null.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #10.

### Fix
* inaccurate `_compatibilityState` for `questionCount`, `attemptInProgress`, `lastAttemptScoreAsPercent`.

### CODE REVIEW

File: js/AssessmentSet.js [hunk 1]
```diff
@@ -133,15 +133,15 @@ export default class AssessmentSet extends ScoringSet {
...
       isPass: this.isPassed,
-      includeInTotalScore: this._config._isScoreIncluded,
+      includeInTotalScore: this.isScoreIncluded,
       assessmentWeight: 1,
       attempts: this.attempts.isInfinite ? 'infinite' : this.attempts.limit,
       attemptsSpent: this.attempts.used,
       attemptsLeft: this.attempts.isInfinite ? 'infinite' : this.attempts.remaining,
-      attemptInProgress: false,
-      lastAttemptScoreAsPercent: null,
+      attemptInProgress: this.attempt.isInProgress,
```
Comment (cahirodoherty-learningpool) [inline js/AssessmentSet.js:143]:
```suggestion
      attemptInProgress: this.attempt?.isInProgress,
```
